### ISSUE TITLE
Help!!

### ISSUE THREAD

**Issue by ghost** [TheEasyPeasy/Java-Runtime-ClassDumper#1]
I compiled it and there was no response after injection

**Comment by TheEasyPeasy** [comment]
@Vortex-CXchenxu Have you created folder at location "C:\JavaClassDump\"?

**Comment by ghost** [comment]
no

**Comment by ghost** [comment]
Do I need to create it manually

**Comment by ghost** [comment]
I still can't use it

**Comment by ghost** [comment]
I created a folder

**Comment by TheEasyPeasy** [comment]
Can you paste console log created after injection?
